services:
  - type: web
    name: restauracion-patrimonio-ia
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.enableCORS false"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
